env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  cgn: readonly
parser: babel-eslint
plugins:
  - jsdoc
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  accessor-pairs: error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing: error
  array-callback-return: error
  array-element-newline:
    - error
    - consistent
  arrow-parens: error
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
  callback-return: 'off'
  camelcase: error
  capitalized-comments: 'off'
  comma-dangle: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity:
    - warn
    - max: 5
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly: error
  default-case: error
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - multiline-arguments
  generator-star-spacing: error
  global-require: error
  handle-callback-err: error
  id-blacklist: error
  id-match: error
  implicit-arrow-linebreak: error
  indent:
    - error
    - tab
    - SwitchCase: 1
  indent-legacy: 'off'
  init-declarations: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  lines-around-comment: 'off'
  lines-around-directive: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-depth: error
  max-len:
    - error
    - code: 120
      comments: 240
  max-lines:
    - warn
    - max: 1000
  max-lines-per-function: warn
  max-nested-callbacks:
    - warn
    - max: 3
  max-params: warn
  max-statements:
    - warn
    - max: 20
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: error
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-console: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: warn
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-fallthrough: warn
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers:
    - error
    - ignore:
      - -1
      - 0
      - 0.5
      - 1
      - 2
      - 100
      - 1000
  no-mixed-requires: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: off
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-sync: error
  no-mixed-spaces-and-tabs: error
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: 
    - error
    - allowAfterThis: true
      allowAfterSuper: true
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: warn
  no-unused-vars: warn
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-warning-comments: warn
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing:
    - error
    - always
  object-property-newline: off
  object-shorthand: error
  one-var: 'off'
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: 'off'
  padding-line-between-statements: error
  prefer-const: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: 'off'
  quote-props: 'off'
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  radix: error
  require-await: 'off'
  require-atomic-updates: 'off'
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi-spacing: error
  semi-style:
    - error
    - last
  sort-keys: 'off'
  sort-vars: off
  space-before-blocks: error
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: false
        FunctionExpression: false
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: 'off'
  strict: error
  switch-colon-spacing: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: error
